import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/providers/ReduxProvider';
import { Header } from '@/components/wrap/HeaderNav/HeaderNav';
import HeroSection from '@/components/home/HeroSection/HeroSection';
import Footer from '@/components/wrap/Footer/Footer';
import { ReactNode } from 'react';
import QueryProvider from '@/providers/QueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <QueryProvider>
      <ReduxProvider>
        <Header/>
        <HeroSection/>

        <main>{children}</main>

        <Footer/>
      </ReduxProvider>
    </QueryProvider>
    </body>
    </html>
  );
}
